apiVersion: v2
name: irl-planner-pro
description: ID5 IRL Attendance App (Go backend + Vue frontend + Postgres)
type: application
version: 0.1.5
appVersion: "0.1.5"
maintainers:
  - name: Oli
keywords:
  - irl
  - attendance
  - offsite
  - id5
